// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo0FqSz-QyZ9cilve7H3UVzDOR0XQvqog',
    appId: '1:451955361631:web:c6d83550a1792d12d598ea',
    messagingSenderId: '451955361631',
    projectId: 'ozbekona-retsept',
    authDomain: 'ozbekona-retsept.firebaseapp.com',
    storageBucket: 'ozbekona-retsept.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA256MTHu39Ukd-WRh5Ak399aWlO0lk9KQ',
    appId: '1:451955361631:android:34eb3b5c2f067d7bd598ea',
    messagingSenderId: '451955361631',
    projectId: 'ozbekona-retsept',
    storageBucket: 'ozbekona-retsept.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz70JPNUHFmR3MkrsyArgCYz1vgyCcjNk',
    appId: '1:451955361631:ios:0f6ec3be97e89363d598ea',
    messagingSenderId: '451955361631',
    projectId: 'ozbekona-retsept',
    storageBucket: 'ozbekona-retsept.firebasestorage.app',
    iosBundleId: 'com.example.ozbekonaRetsept',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz70JPNUHFmR3MkrsyArgCYz1vgyCcjNk',
    appId: '1:451955361631:ios:0f6ec3be97e89363d598ea',
    messagingSenderId: '451955361631',
    projectId: 'ozbekona-retsept',
    storageBucket: 'ozbekona-retsept.firebasestorage.app',
    iosBundleId: 'com.example.ozbekonaRetsept',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo0FqSz-QyZ9cilve7H3UVzDOR0XQvqog',
    appId: '1:451955361631:web:caf86cfae76b1cbdd598ea',
    messagingSenderId: '451955361631',
    projectId: 'ozbekona-retsept',
    authDomain: 'ozbekona-retsept.firebaseapp.com',
    storageBucket: 'ozbekona-retsept.firebasestorage.app',
  );
}
